syntax enable
set background=dark
colorscheme solarized
let g:solarized_termcolors=256

set number
set mouse=a

let mapleader=" "
let maplocalleader=" "

call plug#begin()
"Initialize plugin system
Plug 'bling/vim-airline'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

call plug#end()

set laststatus=2
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ' '
let g:airline#extensions#tabline#left_alt_sep = '|'
