syntax enable
set background=dark
colorscheme solarized
let g:solarized_termcolors=256

set number
set mouse=a

let mapleader=" "
let maplocalleader=" "

call plug#begin()
"Initialize plugin system

call plug#end()
