# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH=$HOME/.zsh/oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
# ZSH_THEME="robbyrussell"
ZSH_THEME="agnoster"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git colored-man-pages)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
export LANG=en_US.UTF-8
export EDITOR='vim'

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias print="echo"
alias log="/var/log"
alias g='grep -C5 --color=auto'
alias pacu="sudo pacman -Suy"
alias paci="sudo pacman -S"
alias tracepath="tracepath -n"
alias winbox="sudo wine /opt/mikrotik/winbox.exe"
alias vimrc="vim ~/.vim/vimrc"
alias zshrc="vim ~/.zshrc"
alias known_hosts="vim ~/.ssh/known_hosts"
alias tel="telnet "
alias ping="sudo ping -i 0.1 -M do"
alias initrc="vim /home/sakat/Document/dotfiles/init.sh"
alias svim='sudo vim'
 alias console="sudo picocom /dev/ttyUSB0 || sudo picocom /dev/ttyUSB1"
alias cpuinfo='lscpu' 
alias fping="fping -g -c 1 "
alias mkt="cd /home/sakat/Dropbox/Mikrotik/Configuration"
export LSCOLORS=cxfxexbxdxegedabagacad
# export LS_COLORS="di=32;48:ln=35;48:so=34;48:pi=31;48:ex=33;48:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43:"
# black                                     =a : 30
# # red                                       =b : 31
# # green                                     =c : 32
# # brown                                     =d : 33
# # blue                                      =e : 34
# # magenta                                   =f : 35
# # cyan                                      =g : 36
# # light grey                                =h : 37
# # bold black, usually shows up as dark grey =A : 40
# # bold red                                  =B : 41
# # bold green                                =C : 42
# # bold brown, usually shows up as yellow    =D : 43
# # bold blue                                 =E : 44
# # bold magenta                              =F : 45
# # bold cyan                                 =G : 46
# # bold light grey; looks like bright white  =H : 47
# # default foreground or background          =x : 48

alias vi="vim"
alias svi="sudo vim"
alias Py="cd /home/sakat/Dropbox/Python"

extract () {
   if [ -f $1 ] ; then
       case $1 in
           *.tar.bz2)   tar xvjf $1    ;;
           *.tar.gz)    tar xvzf $1    ;;
           *.bz2)       bunzip2 $1     ;;
           *.rar)       unrar x $1     ;;
           *.gz)        gunzip $1      ;;
           *.tar)       tar xvf $1     ;;
           *.tbz2)      tar xvjf $1    ;;
           *.tgz)       tar xvzf $1    ;;
           *.zip)       unzip $1       ;;
           *.Z)         uncompress $1  ;;
           *.7z)        7z x $1        ;;
           *)           echo "don't know how to extract '$1'..." ;;
       esac
   else
       echo "'$1' is not a valid file!"
   fi
 }

loss () {
   if [ -f $2 ]; then
  		 while :; do sudo ping -f -c 100 -M do $1 ; sleep 3; done
   else
   		 while :; do sudo ping -f -c 100 -M do $1 -s $2 ; sleep 3; done
  fi
 }

pg (){
# edit ping command	
   if [ -f $2 ]; then
		   ping $1 
   else
		   ping -M do -s $2 $1
   fi
 }
# set -o errexit # <=> set -e make my script exit when a command fails 
# add || true to command that you alow to fail.
# set -o nounset # <=> set -u exit when your script tries to use undeclared 
# set -o xtrace  # <=> set -x to trace what gets excuted. Useful for debugging.
# set -o pipefail # in script to catch mysqldump fails in e.g. mysqldump | gzip. The exit status of last command that threw a non-zero exit code returned.

# #!/usr/bin/env bash is more portable than #!/bin/bash
# Avoid using #!/usr/bin/env bash -e (vs set -e), because whe someone runs your script as bash ./script.sh, the exit on error will be ignored

